services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: shopify-rest-api
    container_name: shopify_web
    restart: unless-stopped
    ports:
      - '8002:8000'
    volumes:
      - /usr/src/app/node_modules
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: shopify_db
    restart: unless-stopped
    ports:
      - '5536:5432'
    environment:
      MONGO_INITDB_ROOT_USERNAME: shopify_user
      MONGO_INITDB_ROOT_PASSWORD: shopify_password
      MONGO_INITDB_DATABASE: admin
